lore:
  health:
    base-health: 20
    keyword: health
  regen:
    keyword: regen
  attack-speed:
    enabled: false
    display-message: false
    message: "你攻击太频繁了"
    base-delay: 2
    keyword: attack speed
  damage:
    keyword: damage
  dodge:
    keyword: evasion
  critical-chance:
    keyword: critical chance
  critical-damage:
    keyword: critical damage
  life-steal:
    keyword: life steal
  armor:
    keyword: armor
  restriction:
    keyword: type
    display-message: false
    message: "你不能使用%itemname%"
  level:
    keyword: level
    message: "你的等级不足以使用此物品"
  unlimitdura:
    keyword: unlimitdura
  duraregen:
    keyword: duraregen
  exp:
    keyword: exp
  bound:
    keyword: bound
    message: "本物品只能由{name}使用"
  range:
    keyword: range
  dura:
    keyword: dura
    message: "已达到耐久上限"
integration:
  permissionshealth: false