name: LoreAttributes
main: com.settingdust.loreattr.LoreAttributes
version: 1.4.0
description: Apply stats to weapons and armor!
authors: [Nighteyes604,LordPhrozen,SettingDust]
softdepend:
commands:
  hp:
    description: Display health of yourself.
  lorestats:
    description: Display the stat benefits of your lore.